spring:
  profiles:
    group:
      local:
        - local
        - aws
        - oauth
      prod :
        - aws
        - oauth
        - db
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL57Dialect
      format_sql: true
      default_batch_fetch_size: 100
    generate-ddl: true
  data:
    web:
      pageable:
        one-indexed-parameters: true
  devtools:
    livereload:
      enabled: 'true'
# server
server:
  address: localhost
  servlet:
    encoding:
      force: 'true'
      charset: UTF-8
      enabled: 'true'
    contextPath: /
  port: '8080'
build:
  date: '@build.date@'
# log
logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
      apache:
        tiles: INFO
      hibernate:
        SQL: DEBUG
    root: INFO
    com:
      samsung:
        security: DEBUG
      amazonaws:
        util:
          EC2MetadataUtils: ERROR
  file:
    name: ./ssafy-web.log
# jwt token
jwt:
  access-token-props:
    secret: 
    expiration-time-milli-sec: 
  refresh-token-props:
    expiration-time-milli-sec: 
    secret: 
# openvidu
openvidu:
  url: https://i7a406.p.ssafy.io:5443
  secret: A406
---
spring.config.activate.on-profile: local
# database
spring:
  flyway:
    baseline-on-migrate: 
    schemas: 
    locations: 
    encoding: UTF-8
    baseline-version: 
    url: 
    validate-on-migrate:
    user: 
    password: 
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      password: 
      username: 
    url: 
  redis:
    host: 
    port: 
    password: 
